//! The parsers on small synthetic sessions, one per format and generation,
//! each record shaped as its tool writes it (never a real chat).

use super::*;

fn jsonl(lines: &[Value]) -> impl Iterator<Item = Value> + '_ {
    lines.iter().cloned()
}

fn said(c: &Conversation) -> Vec<(Role, &str)> {
    c.messages.iter().map(|m| (m.role, m.text.as_str())).collect()
}

const T0: &str = "2026-03-01T10:00:00.000Z";
const T0_MS: i64 = 1_772_359_200_000;

fn at(s: i64) -> String {
    let ms = T0_MS + s * 1000;
    let (y, m, d) = fragment_core::cron::civil(ms.div_euclid(86_400_000));
    let t = ms.rem_euclid(86_400_000) / 1000;
    format!("{y:04}-{m:02}-{d:02}T{:02}:{:02}:{:02}.000Z", t / 3600, t / 60 % 60, t % 60)
}

/// Goal: the times every format writes read as one clock. Method: ISO 8601
/// with and without a zone, fractions, offsets, epoch seconds and
/// milliseconds, and malformed ones.
#[test]
fn times_read_as_utc_milliseconds() {
    assert_eq!(parse_time(T0), Some(T0_MS));
    assert_eq!(parse_time("2026-03-01T10:00:00Z"), Some(T0_MS));
    assert_eq!(parse_time("2026-03-01T10:00:00.123456+00:00"), Some(T0_MS + 123));
    assert_eq!(parse_time("2026-03-01T11:30:00+01:30"), Some(T0_MS), "an offset is taken away");
    assert_eq!(parse_time("2026-03-01T05:00:00-0500"), Some(T0_MS));
    assert_eq!(parse_time("2026-03-01 10:00:00.5"), Some(T0_MS + 500), "no zone: UTC");
    assert_eq!(parse_time("2026-03-01"), Some(T0_MS - 10 * 3_600_000));
    assert_eq!(parse_time("1970-01-01T00:00:00Z"), Some(0));
    assert_eq!(parse_time("2000-02-29T00:00:00Z"), Some(951_782_400_000), "a leap day");
    for bad in ["", "2026-3-1", "2026-13-01", "2026-03-01T25:00:00Z", "2026-03-01T10:00:00Q", "2026-03-01T10:00:00.Z", "yesterday"] {
        assert_eq!(parse_time(bad), None, "{bad:?}");
    }
    assert_eq!(time_of(&json!(1_772_359_200.25)), Some(T0_MS + 250), "Hermes's seconds");
    assert_eq!(time_of(&json!(T0_MS)), Some(T0_MS), "Codex's milliseconds");
    assert_eq!(time_of(&json!(-5)), None);
    assert_eq!(at(61), "2026-03-01T10:01:01.000Z");
}

/// Goal: a message the CLI caps is the one the mind logs (its `capText`):
/// head and tail kept, the cut counted. Method: texts at, under and over
/// the cap, in characters, not bytes.
#[test]
fn caps_keep_head_and_tail_as_the_mind_does() {
    let at_cap = "é".repeat(CAP);
    assert_eq!(cap_text(&at_cap, CAP), at_cap, "at the cap, in characters, nothing is cut");
    let long = format!("{}{}", "a".repeat(20_000), "b".repeat(20_000));
    let capped = cap_text(&long, CAP);
    assert_eq!(capped.chars().count() <= CAP, true);
    assert!(capped.starts_with(&"a".repeat(14_960)) && capped.ends_with(&"b".repeat(14_960)));
    assert!(capped.contains("\n\n[… 10080 characters cut here …]\n\n"), "{}", &capped[14_950..15_010]);
}

/// Goal: a Claude Code session keeps the person's words and each turn's
/// final reply, nothing the harness or the tools wrote. Method: one
/// session with each kind of record its files hold.
#[test]
fn claude_code_keeps_words_and_final_replies() {
    let s = "11111111-1111-4111-8111-111111111111";
    let user = |t: i64, text: &str, uuid: &str| json!({ "type": "user", "sessionId": s, "uuid": uuid, "timestamp": at(t), "origin": { "kind": "human" }, "message": { "role": "user", "content": text } });
    let assistant = |t: i64, id: &str, content: Value| json!({ "type": "assistant", "sessionId": s, "uuid": format!("a{t}"), "timestamp": at(t), "message": { "id": id, "role": "assistant", "model": "claude", "content": content } });
    let lines = vec![
        json!({ "type": "file-history-snapshot", "messageId": "x", "snapshot": {} }),
        json!({ "type": "user", "sessionId": s, "uuid": "m0", "timestamp": at(0), "isMeta": true, "message": { "role": "user", "content": "Caveat: The messages below were generated by the user while running local commands." } }),
        user(1, "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>", "u1"),
        user(2, "plan the garden beds<system-reminder>\nthe date is today\n</system-reminder>", "u2"),
        assistant(3, "msg_1", json!([{ "type": "thinking", "thinking": "hmm" }, { "type": "text", "text": "Let me look at the plot first." }])),
        assistant(4, "msg_1", json!([{ "type": "tool_use", "id": "toolu_1", "name": "Read", "input": { "file_path": "plot.md" } }])),
        json!({ "type": "user", "sessionId": s, "uuid": "r1", "timestamp": at(5), "toolUseResult": { "stdout": "3 beds" }, "message": { "role": "user", "content": [{ "type": "tool_result", "tool_use_id": "toolu_1", "content": "3 beds" }] } }),
        assistant(6, "msg_2", json!([{ "type": "text", "text": "Three beds:" }])),
        assistant(7, "msg_2", json!([{ "type": "text", "text": "tomatoes, basil, beans." }])),
        json!({ "type": "attachment", "sessionId": s, "uuid": "q1", "timestamp": at(8), "attachment": { "type": "queued_command", "commandMode": "prompt", "prompt": "and the herbs?", "origin": { "kind": "human" }, "source_uuid": "q-src" } }),
        json!({ "type": "attachment", "sessionId": s, "uuid": "q2", "timestamp": at(9), "attachment": { "type": "queued_command", "commandMode": "task-notification", "prompt": "<task-notification>done</task-notification>" } }),
        assistant(10, "msg_3", json!([{ "type": "text", "text": "Herbs go by the door." }])),
        // a subagent's report starts a turn of the harness's: its words go, the reply stays
        json!({ "type": "user", "sessionId": s, "uuid": "n1", "timestamp": at(11), "origin": { "kind": "task-notification" }, "message": { "role": "user", "content": "<task-notification>agent done</task-notification>" } }),
        assistant(12, "msg_4", json!([{ "type": "text", "text": "The soil test came back: pH 6.5." }])),
        user(13, "[Request interrupted by user]", "u3"),
        json!({ "type": "assistant", "sessionId": s, "uuid": "e1", "timestamp": at(14), "isApiErrorMessage": true, "message": { "id": "e", "model": "<synthetic>", "content": [{ "type": "text", "text": "API Error: 500" }] } }),
        user(15, "<command-name>/review</command-name>\n<command-args>the north bed</command-args>", "u4"),
        assistant(16, "msg_5", json!([{ "type": "text", "text": "Checking." }, { "type": "tool_use", "id": "toolu_2", "name": "Bash", "input": {} }])),
        // a sidechain (a subagent's own turn) is not this chat
        json!({ "type": "user", "sessionId": s, "uuid": "sc", "isSidechain": true, "timestamp": at(17), "message": { "role": "user", "content": "subagent prompt" } }),
        json!({ "type": "custom-title", "sessionId": s, "customTitle": "Garden  beds" }),
    ];
    let convs = claude_code(s, jsonl(&lines));
    assert_eq!(convs.len(), 1);
    let c = &convs[0];
    assert_eq!((c.source, c.id.as_str(), c.title.as_deref(), c.started), (Source::ClaudeCode, s, Some("Garden beds"), T0_MS + 2000));
    assert_eq!(
        said(c),
        [
            (Role::User, "plan the garden beds"),
            (Role::Assistant, "Three beds:\n\ntomatoes, basil, beans."),
            (Role::User, "and the herbs?"),
            (Role::Assistant, "Herbs go by the door."),
            (Role::Assistant, "The soil test came back: pH 6.5."),
            (Role::User, "/review the north bed"),
        ],
        "narration before a tool call, the harness's records, a sidechain and an unfinished turn's narration are dropped"
    );
    assert_eq!(c.messages[1].at, T0_MS + 6000, "a reply's time is its first part's");
    assert_eq!(c.messages[0].key.as_deref(), Some("u2"));
}

/// Goal: a session forked from another carries that one's records under its
/// id: they are that conversation's, merged with its own file once.
/// Method: an original and a fork holding a copy of its first turn.
#[test]
fn claude_code_forks_merge_into_their_original() {
    let (a, b) = ("aaaaaaaa-0000-4000-8000-000000000000", "bbbbbbbb-0000-4000-8000-000000000000");
    let rec = |sid: &str, t: i64, kind: &str, text: &str| {
        let content = if kind == "user" { json!(text) } else { json!([{ "type": "text", "text": text }]) };
        json!({ "type": kind, "sessionId": sid, "uuid": format!("{sid}-{t}"), "timestamp": at(t), "message": { "id": format!("m{t}"), "role": kind, "content": content } })
    };
    let original = vec![rec(a, 0, "user", "first question"), rec(a, 1, "assistant", "first answer"), rec(a, 2, "user", "second question"), rec(a, 3, "assistant", "second answer")];
    let fork = vec![rec(a, 0, "user", "first question"), rec(a, 1, "assistant", "first answer"), rec(b, 10, "user", "a fork's own question"), rec(b, 11, "assistant", "its answer")];
    let mut convs = claude_code(b, jsonl(&fork));
    convs.extend(claude_code(a, jsonl(&original)));
    assert_eq!(convs.iter().map(|c| c.id.as_str()).collect::<Vec<_>>(), [a, b, a], "the fork's file holds two conversations");
    let ready = prepare(convs, None, None);
    assert_eq!(ready.len(), 2);
    assert_eq!(said(&ready[0]).len(), 4, "the original once, its copy merged away: {:?}", said(&ready[0]));
    assert_eq!(said(&ready[1]), [(Role::User, "a fork's own question"), (Role::Assistant, "its answer")]);
}

/// Goal: claude.ai's export: each conversation's human messages and the
/// assistant's text, its tool use and thinking dropped. Method: one
/// conversation with a search in its reply, one with no human words.
#[test]
fn claude_export_reads_each_conversation() {
    let export = json!([
        {
            "uuid": "c-1", "name": "Bread", "created_at": at(0), "updated_at": at(9),
            "chat_messages": [
                { "uuid": "h1", "sender": "human", "text": "how long to proof sourdough?", "content": [{ "type": "text", "text": "how long to proof sourdough?" }], "created_at": at(1), "attachments": [] },
                { "uuid": "a1", "sender": "assistant", "text": "", "created_at": at(2), "content": [
                    { "type": "thinking", "thinking": "..." },
                    { "type": "text", "text": "Let me check." },
                    { "type": "tool_use", "name": "web_search", "input": { "query": "proof" } },
                    { "type": "tool_result", "content": [{ "type": "text", "text": "results" }] },
                    { "type": "text", "text": "4 to 6 hours at room temperature." }
                ] },
                { "uuid": "h2", "sender": "human", "text": "thanks", "content": [], "created_at": at(3) }
            ]
        },
        { "uuid": "c-2", "name": "", "created_at": at(5), "chat_messages": [] }
    ]);
    let convs = claude_export(&export);
    assert_eq!(convs.len(), 1, "a conversation with no words of the person's is none");
    let c = &convs[0];
    assert_eq!((c.id.as_str(), c.title.as_deref(), c.started), ("c-1", Some("Bread"), T0_MS));
    assert_eq!(
        said(c),
        [(Role::User, "how long to proof sourdough?"), (Role::Assistant, "Let me check.\n\n4 to 6 hours at room temperature."), (Role::User, "thanks")]
    );
}

/// Goal: Codex's newest rollouts (turn items): the person's words without
/// what the app put above them, the final answer and not the commentary, no
/// items of another thread. Method: two turns, one aborted.
#[test]
fn codex_turn_items() {
    let id = "019c0000-0000-7000-8000-000000000001";
    let item = |t: i64, thread: &str, item: Value| json!({ "timestamp": at(t), "type": "event_msg", "payload": { "type": "item_completed", "thread_id": thread, "turn_id": "t", "completed_at_ms": T0_MS + t * 1000, "item": item } });
    let text = |s: &str| json!([{ "type": "text", "text": s, "text_elements": [] }]);
    let lines = vec![
        json!({ "timestamp": at(0), "type": "session_meta", "payload": { "id": id, "timestamp": at(0), "source": "vscode", "originator": "Codex Desktop", "base_instructions": { "text": "You are Codex" } } }),
        json!({ "timestamp": at(0), "type": "response_item", "payload": { "type": "message", "role": "user", "content": [{ "type": "input_text", "text": "<environment_context>cwd</environment_context>" }] } }),
        item(1, id, json!({ "type": "UserMessage", "id": "item-1", "content": text("# Files mentioned by the user:\n## a.rs\n## My request for Codex:\nrename the crate") })),
        item(2, id, json!({ "type": "AgentMessage", "id": "item-2", "phase": "commentary", "content": [{ "type": "Text", "text": "Looking at Cargo.toml." }] })),
        item(3, id, json!({ "type": "CommandExecution", "id": "item-3", "command": "rg name", "aggregated_output": "", "exit_code": 0 })),
        item(4, id, json!({ "type": "Reasoning", "id": "item-4", "summary_text": [] })),
        item(5, id, json!({ "type": "AgentMessage", "id": "item-5", "phase": "final_answer", "content": [{ "type": "Text", "text": "Renamed it to garden." }] })),
        item(6, "019c-another-thread", json!({ "type": "UserMessage", "id": "item-1", "content": text("a parent's words") })),
        item(7, id, json!({ "type": "UserMessage", "id": "item-6", "content": text("now publish it") })),
        item(8, id, json!({ "type": "AgentMessage", "id": "item-7", "phase": "commentary", "content": [{ "type": "Text", "text": "Publishing." }] })),
        item(9, id, json!({ "type": "McpToolCall", "id": "item-8", "tool": "x" })),
    ];
    let c = codex(id, jsonl(&lines)).expect("a conversation");
    assert_eq!((c.id.as_str(), c.started), (id, T0_MS));
    assert_eq!(said(&c), [(Role::User, "rename the crate"), (Role::Assistant, "Renamed it to garden."), (Role::User, "now publish it")]);
    let mut sub = lines.clone();
    sub[0]["payload"]["source"] = json!({ "subagent": { "thread_spawn": { "parent_thread_id": "p" } } });
    assert_eq!(codex(id, jsonl(&sub)), None, "a subagent's rollout is an agent's words");
}

/// Goal: Codex's earlier rollouts, by events and by response items alone,
/// and its first format with no record types. Method: one turn each.
#[test]
fn codex_events_and_response_items() {
    let meta = json!({ "timestamp": at(0), "type": "session_meta", "payload": { "id": "s-ev", "timestamp": at(0), "source": "cli", "instructions": "" } });
    let ev = |t: i64, p: Value| json!({ "timestamp": at(t), "type": "event_msg", "payload": p });
    let events = vec![
        meta.clone(),
        ev(1, json!({ "type": "user_message", "message": "<user_instructions>be terse</user_instructions>" })),
        ev(2, json!({ "type": "user_message", "message": "fix the build", "kind": "plain" })),
        ev(3, json!({ "type": "agent_message", "message": "Running cargo." })),
        ev(4, json!({ "type": "exec_command_end", "exit_code": 0 })),
        ev(5, json!({ "type": "task_complete", "last_agent_message": "Fixed: a missing semicolon." })),
    ];
    let c = codex("s-ev", jsonl(&events)).expect("a conversation");
    assert_eq!(said(&c), [(Role::User, "fix the build"), (Role::Assistant, "Fixed: a missing semicolon.")], "task_complete is the reply when the last words were narration");

    let ri = |t: i64, p: Value| json!({ "timestamp": at(t), "type": "response_item", "payload": p });
    let items = vec![
        meta,
        ri(1, json!({ "type": "message", "role": "user", "content": [{ "type": "input_text", "text": "# AGENTS.md instructions for /repo\n\nbe kind" }, { "type": "input_text", "text": "<environment_context>\n<cwd>/repo</cwd>\n</environment_context>" }] })),
        ri(2, json!({ "type": "message", "role": "user", "content": [{ "type": "input_text", "text": "add a test" }] })),
        ri(3, json!({ "type": "reasoning", "summary": [] })),
        ri(4, json!({ "type": "message", "role": "assistant", "content": [{ "type": "output_text", "text": "I'll read lib.rs." }] })),
        ri(5, json!({ "type": "function_call", "name": "shell", "arguments": "{}" })),
        ri(6, json!({ "type": "function_call_output", "output": "ok" })),
        ri(7, json!({ "type": "message", "role": "assistant", "content": [{ "type": "output_text", "text": "Added one test." }] })),
        ri(8, json!({ "type": "message", "role": "developer", "content": [{ "type": "input_text", "text": "approval policy" }] })),
    ];
    let c = codex("s-ev", jsonl(&items)).expect("a conversation");
    assert_eq!(said(&c), [(Role::User, "add a test"), (Role::Assistant, "Added one test.")]);

    let first = vec![
        json!({ "id": "s-old", "timestamp": at(0), "instructions": null }),
        json!({ "record_type": "state" }),
        json!({ "type": "message", "role": "user", "content": [{ "type": "input_text", "text": "hello codex" }] }),
        json!({ "type": "message", "role": "assistant", "content": [{ "type": "output_text", "text": "hello" }] }),
    ];
    let c = codex("ignored", jsonl(&first)).expect("a conversation");
    assert_eq!((c.id.as_str(), said(&c)), ("s-old", vec![(Role::User, "hello codex"), (Role::Assistant, "hello")]));
    assert!(c.messages[0].at > T0_MS && c.messages[1].at > c.messages[0].at, "no record time: the session's, in order");
}

/// Goal: Hermes's export: a compaction's continuation is the same
/// conversation; rows undone, summaries, injected memory and skill
/// scaffolds are not the person's words; an agent's session is none.
/// Method: a chain of two sessions and a subagent's.
#[test]
fn hermes_export_follows_compaction_chains() {
    let t = |s: i64| json!((T0_MS / 1000 + s) as f64 + 0.5);
    let sessions = vec![
        json!({ "id": "20260301_100000_aaaaaa", "source": "cli", "title": "DNS", "started_at": t(0), "end_reason": "compression", "parent_session_id": null, "messages": [
            { "role": "user", "content": "move DNS to cloudflare\n\n<memory-context>\n- prefers terse\n</memory-context>", "timestamp": t(1), "active": 1, "compacted": 1, "message_uid": "u1" },
            { "role": "assistant", "content": "", "tool_calls": "[{\"id\": \"c1\", \"type\": \"function\", \"function\": {\"name\": \"terminal\"}}]", "timestamp": t(2), "active": 1, "message_uid": "a1" },
            { "role": "tool", "content": "ok", "tool_call_id": "c1", "timestamp": t(3), "active": 1 },
            { "role": "assistant", "content": "<think>easy</think>Moved: the zone is active.", "timestamp": t(4), "active": 1, "message_uid": "a2" },
            { "role": "user", "content": "oops, undone", "timestamp": t(5), "active": 0, "compacted": 0, "message_uid": "u2" }
        ] }),
        json!({ "id": "20260301_110000_bbbbbb", "source": "cli", "title": null, "started_at": t(3600), "end_reason": null, "parent_session_id": "20260301_100000_aaaaaa", "messages": [
            { "role": "user", "content": "[CONTEXT COMPACTION — REFERENCE ONLY] earlier: DNS moved", "timestamp": t(3601), "active": 1, "_compressed_summary": 1, "message_uid": "s1" },
            { "role": "assistant", "content": "Moved: the zone is active.", "timestamp": t(4), "active": 1, "message_uid": "a2" },
            { "role": "user", "content": "[IMPORTANT: The user has invoked the \"dig\" skill... The user has provided the following instruction alongside the skill invocation: check the MX records", "timestamp": t(3602), "active": 1, "message_uid": "u3" },
            { "role": "assistant", "content": "MX points at fastmail.", "timestamp": t(3603), "active": 1, "display_kind": null, "message_uid": "a3" },
            { "role": "user", "content": "switched model", "timestamp": t(3604), "active": 1, "display_kind": "model_switch", "message_uid": "u4" }
        ] }),
        json!({ "id": "20260301_120000_cccccc", "source": "subagent", "started_at": t(7200), "messages": [{ "role": "user", "content": "do a subtask", "timestamp": t(7201) }] }),
    ];
    let convs = hermes_export(&sessions);
    assert_eq!(convs.len(), 1, "the subagent's session is none; the continuation joins its parent");
    let c = &convs[0];
    assert_eq!((c.id.as_str(), c.title.as_deref(), c.started), ("20260301_100000_aaaaaa", Some("DNS"), T0_MS + 500));
    assert_eq!(
        said(c),
        [
            (Role::User, "move DNS to cloudflare"),
            (Role::Assistant, "Moved: the zone is active."),
            (Role::User, "check the MX records"),
            (Role::Assistant, "MX points at fastmail."),
        ]
    );
}

/// Goal: Hermes's older files: a snapshot (no message times) and a gateway
/// transcript. Method: one turn each.
#[test]
fn hermes_older_files() {
    let snap = json!({ "session_id": "20260310_091523_a1b2c3", "platform": "cli", "session_start": "2026-03-01T10:00:00.000000", "messages": [
        { "role": "user", "content": "List my repos" },
        { "role": "assistant", "content": "", "tool_calls": [{ "id": "call_9", "type": "function", "function": { "name": "terminal", "arguments": "{}" } }] },
        { "role": "tool", "content": "fragment\nfinite", "tool_call_id": "call_9" },
        { "role": "assistant", "content": "Two: fragment and finite." }
    ] });
    let c = hermes_snapshot(&snap).expect("a conversation");
    assert_eq!(said(&c), [(Role::User, "List my repos"), (Role::Assistant, "Two: fragment and finite.")]);
    assert_eq!((c.started, c.messages[0].at), (T0_MS, T0_MS + 1), "no message times: the session's start, in order");
    let lines = vec![
        json!({ "role": "session_meta", "tools": [], "platform": "telegram", "timestamp": "2026-03-01T10:00:00" }),
        json!({ "role": "user", "content": "what did we decide about DNS", "timestamp": "2026-03-01T10:00:00" }),
        json!({ "role": "assistant", "content": "Cloudflare.", "finish_reason": "stop", "timestamp": "2026-03-01T10:00:00" }),
    ];
    let c = hermes_transcript("20260312_200105_abcdef", jsonl(&lines)).expect("a conversation");
    assert_eq!(said(&c), [(Role::User, "what did we decide about DNS"), (Role::Assistant, "Cloudflare.")]);
    assert!(c.messages[1].at > c.messages[0].at, "a turn's shared time keeps its order");
}

fn conv(source: Source, id: &str, started: i64, messages: &[(Role, &str)]) -> Conversation {
    Conversation {
        source,
        id: id.into(),
        title: None,
        started,
        messages: messages.iter().enumerate().map(|(k, (role, text))| Message { role: *role, text: (*text).into(), at: started + k as i64, key: None }).collect(),
    }
}

/// Goal: what goes to the mind is ordered, without repeated pastes, capped,
/// and bounded by --since and --limit. Method: three conversations out of
/// order, one repeating another's long paste.
#[test]
fn prepare_orders_dedups_caps_and_limits() {
    let paste = "x ".repeat(PASTE_MIN_BYTES);
    let long = "y".repeat(CAP + 100);
    let convs = vec![
        conv(Source::Codex, "late", T0_MS + 2000, &[(Role::User, &paste), (Role::User, "and this"), (Role::Assistant, &long)]),
        conv(Source::ClaudeCode, "early", T0_MS, &[(Role::User, &paste), (Role::Assistant, "read it")]),
        conv(Source::Hermes, "only-replies", T0_MS + 1000, &[(Role::Assistant, "hi")]),
    ];
    let ready = prepare(convs.clone(), None, None);
    assert_eq!(ready.iter().map(|c| c.id.as_str()).collect::<Vec<_>>(), ["early", "late"], "oldest first; one with no words of the person's goes");
    assert_eq!(ready[1].messages.len(), 2, "the paste repeated (whitespace aside) is dropped where it repeats");
    assert!(ready[1].messages[1].text.chars().count() <= CAP && ready[1].messages[1].text.contains("characters cut here"), "a message is capped at CAP characters");
    assert_eq!(prepare(convs.clone(), Some(T0_MS + 1), None).iter().map(|c| c.id.as_str()).collect::<Vec<_>>(), ["late"]);
    assert_eq!(prepare(convs, None, Some(1)).iter().map(|c| c.id.as_str()).collect::<Vec<_>>(), ["early"]);
}

/// Goal: a conversation goes in parts the `import` operation takes: at most
/// PART_MESSAGES_MAX messages and PART_MAX_BYTES of input each, from where
/// the mind stopped. Method: many small messages, and a few large ones.
#[test]
fn parts_fit_the_operation() {
    let texts: Vec<String> = (0..150).map(|k| format!("message {k}")).collect();
    let small = conv(Source::Codex, "s", T0_MS, &texts.iter().map(|t| (Role::User, t.as_str())).collect::<Vec<_>>());
    assert_eq!(parts(&small, 0), [(0, 64), (64, 128), (128, 150)]);
    assert_eq!(parts(&small, 100), [(100, 150)], "from where the mind stopped");
    assert!(parts(&small, 150).is_empty());
    let big = "z".repeat(CAP);
    let large = conv(Source::Codex, "l", T0_MS, &vec![(Role::Assistant, big.as_str()); 20]);
    let p = parts(&large, 0);
    assert_eq!(p.first(), Some(&(0, 6)), "six 30 000-character messages to a part");
    for (a, b) in p {
        let input = part_input(&large, a, &large.messages[a..b]).to_string();
        assert!(input.len() <= PART_MAX_BYTES, "{} bytes", input.len());
    }
}

/// Goal: the dry run's estimate counts what the compactor will do. Method:
/// short messages (free nodes and free merges) and long ones (calls).
#[test]
fn estimate_counts_calls_and_free_nodes() {
    let long = "w".repeat(NODE + 1);
    let c = conv(Source::Codex, "e", T0_MS, &[(Role::User, "hi"), (Role::Assistant, "hello"), (Role::User, &long), (Role::Assistant, &long)]);
    let e = estimate(&[c]);
    assert_eq!((e.messages, e.level0_calls, e.level0_batches), (4, 2, 1), "two long messages, one batch");
    assert_eq!((e.merges_free, e.merge_calls), (2, 1), "hi+hello fit together, and with the long pair's line; the long pair does not");
    assert!(e.list_cached > 0 && e.list_cached <= e.list_uncached && e.list_uncached < e.charge_uncached);
}

/// Goal: files are told apart by what they hold. Method: one of each
/// format written to a scratch folder, and files of none.
#[test]
fn detects_each_format() {
    let dir = std::env::temp_dir().join(format!("fragment-import-{:016x}", rand::random::<u64>()));
    std::fs::create_dir_all(dir.join("subagents")).unwrap();
    let write = |name: &str, text: &str| {
        let p = dir.join(name);
        std::fs::write(&p, text).unwrap();
        p
    };
    let cases = [
        ("s.jsonl", r#"{"type":"summary","summary":"x","leafUuid":"u"}"#, Some(Format::ClaudeCode)),
        ("c.jsonl", r#"{"type":"user","sessionId":"s","message":{"role":"user","content":"hi"}}"#, Some(Format::ClaudeCode)),
        ("rollout-x.jsonl", r#"{"timestamp":"t","type":"session_meta","payload":{"id":"x"}}"#, Some(Format::Codex)),
        ("rollout-old.jsonl", r#"{"id":"x","timestamp":"t","instructions":null}"#, Some(Format::Codex)),
        ("h.jsonl", r#"{"id":"20260301_1","source":"cli","started_at":1.0,"messages":[]}"#, Some(Format::HermesExport)),
        ("g.jsonl", r#"{"role":"session_meta","platform":"telegram","timestamp":"2026-03-01T10:00:00"}"#, Some(Format::HermesTranscript)),
        ("session_1.json", r#"{"session_id":"1","messages":[]}"#, Some(Format::HermesSnapshot)),
        ("conversations.json", "[]", Some(Format::ClaudeExport)),
        ("history.jsonl", r#"{"session_id":"s","ts":1,"text":"a prompt"}"#, None),
        ("projects.json", "[]", None),
    ];
    for (name, text, want) in cases {
        assert_eq!(detect(&write(name, text)).unwrap(), want, "{name}");
    }
    let db = write("state.db", "SQLite format 3\0rest");
    assert_eq!(detect(&db).unwrap(), Some(Format::Sqlite));
    write("subagents/agent-a.jsonl", r#"{"type":"user","sessionId":"s"}"#);
    let listed = files(std::slice::from_ref(&dir)).unwrap();
    assert!(!listed.iter().any(|p| p.starts_with(dir.join("subagents"))), "a subagents folder is a Claude Code agent's own");
    assert_eq!(listed.len(), cases.len() + 1, "each .json, .jsonl and .db, and nothing else: {listed:?}");
    let (convs, found) = read(&[dir.clone()], None).unwrap();
    assert_eq!(found.sqlite, [db.display().to_string()]);
    assert!(convs.is_empty(), "{convs:?}");
    std::fs::remove_dir_all(&dir).unwrap();
}
