//! Platform AI (phase 2 slice F): OpenRouter text, images, and video as a
//! job's steps, paid with the fragment's own `OPENROUTER_API_KEY` secret
//! (opened at the egress point, like every secret; a person's own key
//! replaces it once people connect OpenRouter, docs/secrets.md). Generated
//! images and videos are files: written to `main` (a blob when 1 MiB or
//! more), so they sync to folders like anything else.

use std::time::Duration;

use base64::Engine;
use fragment_core::blob;
use serde_json::{json, Value};
use worker::*;

use crate::error::CellError;
use crate::files::FileWrite;
use crate::fragment::FragmentCell;
use crate::jobs::{permanent, StepFail};
use crate::ops::JOB_ID_PREFIX;

pub const IMAGE_MODEL: &str = "google/gemini-3.1-flash-lite-image";
pub const VIDEO_MODEL: &str = "minimax/hailuo-3-max";
/// A generated file the platform stores (a video is a blob).
const MEDIA_MAX_BYTES: usize = 64 * 1024 * 1024;
const CALL_TIMEOUT: Duration = Duration::from_secs(120);
const KEY_SECRET: &str = "OPENROUTER_API_KEY";

/// A failed OpenRouter answer: passing (429, 5xx) or lasting.
fn failure(status: u16, body: &[u8]) -> StepFail {
    let v: Value = serde_json::from_slice(body).unwrap_or(Value::Null);
    let message = v["error"]["message"].as_str().map(str::to_string).unwrap_or_else(|| String::from_utf8_lossy(body).chars().take(200).collect());
    match status {
        429 | 500..=599 => StepFail::Retry(format!("OpenRouter answered {status}: {message}")),
        402 => permanent(format!("OpenRouter: out of credits ({message})")),
        _ => permanent(format!("OpenRouter answered {status}: {message}")),
    }
}

impl FragmentCell {
    /// One OpenRouter call, with the fragment's key.
    async fn openrouter(&self, method: Method, url: &str, body: Option<&Value>) -> Result<(u16, Vec<u8>), StepFail> {
        let key = self
            .open_secret(KEY_SECRET)
            .map_err(|e| StepFail::Retry(e.message))?
            .ok_or_else(|| permanent(format!("set the fragment's {KEY_SECRET} secret to use OpenRouter (`fragment secret set`)")))?;
        let key = String::from_utf8(key).map_err(|_| permanent(format!("{KEY_SECRET} is not text")))?;
        let headers = Headers::new();
        headers.set("authorization", &format!("Bearer {}", key.trim())).map_err(|e| permanent(e.to_string()))?;
        headers.set("x-openrouter-title", "fragment").map_err(|e| permanent(e.to_string()))?;
        let mut init = RequestInit::new();
        init.with_method(method).with_headers(headers);
        if let Some(b) = body {
            init.headers.set("content-type", "application/json").map_err(|e| permanent(e.to_string()))?;
            init.with_body(Some(b.to_string().into()));
        }
        let req = Request::new_with_init(url, &init).map_err(|e| permanent(e.to_string()))?;
        let mut resp = crate::cs::fetch(req, CALL_TIMEOUT).await.map_err(|e| StepFail::Retry(format!("OpenRouter: {}", e.message)))?;
        let status = resp.status_code();
        let bytes = resp.bytes().await.map_err(|e| StepFail::Retry(format!("OpenRouter: {e}")))?;
        Ok((status, bytes))
    }

    fn api(&self, path: &str) -> String {
        format!("{}/api/v1/{path}", self.cfg.openrouter_url)
    }

    /// Writes generated bytes to `path` on `main` once per step: in git, or
    /// as a blob and its pointer when 1 MiB or more.
    async fn store_media(&self, run: &Value, index: i64, path: &str, bytes: Vec<u8>) -> Result<Value, StepFail> {
        let retry = |e: CellError| StepFail::Retry(e.message);
        let sha = blob::sha256_hex(&bytes);
        let size = bytes.len() as u64;
        let content = if bytes.len() >= blob::BLOB_MIN_BYTES {
            self.put_blob_bytes(&sha, bytes).await.map_err(retry)?;
            blob::pointer(&sha, size).into_bytes()
        } else {
            bytes
        };
        let run_id = run["id"].as_i64().unwrap_or(0);
        let key = format!("{JOB_ID_PREFIX}{run_id}:{index}");
        let message = format!("{} run {run_id}: generated {path}", run["op"].as_str().unwrap_or(""));
        let writes = [FileWrite { path: path.to_string(), bytes: Some(content) }];
        let depth = run["depth"].as_u64().unwrap_or(0) as u32;
        self.commit_files(&key, &writes, &Default::default(), &message, run["principal"].as_str().unwrap_or(""), depth).await.map_err(retry)?;
        Ok(json!({ "path": path, "size": size, "sha256": sha }))
    }

    /// `job.ai.*` steps.
    pub(crate) async fn step_ai(&self, run: &Value, index: i64, kind: &str, args: &Value) -> Result<Value, StepFail> {
        match kind {
            "ai.text" => {
                let model = args["model"].as_str().ok_or_else(|| permanent("ai.text needs a model (an OpenRouter model id)"))?;
                let messages = match (&args["messages"], args["prompt"].as_str()) {
                    (Value::Array(m), _) => Value::Array(m.clone()),
                    (_, Some(p)) => json!([{ "role": "user", "content": p }]),
                    _ => return Err(permanent("ai.text needs messages or a prompt")),
                };
                let mut body = json!({ "model": model, "messages": messages });
                // OpenRouter's reasoning control, as the job gave it (a
                // reasoning model can spend a small cap thinking)
                if args["reasoning"].is_object() {
                    body["reasoning"] = args["reasoning"].clone();
                }
                if let Some(n) = args["max_tokens"].as_u64() {
                    body["max_tokens"] = json!(n);
                }
                let (status, bytes) = self.openrouter(Method::Post, &self.api("chat/completions"), Some(&body)).await?;
                let v: Value = serde_json::from_slice(&bytes).unwrap_or(Value::Null);
                if status != 200 || v.get("error").is_some() {
                    return Err(failure(if status == 200 { 502 } else { status }, &bytes));
                }
                let text = v["choices"][0]["message"]["content"].as_str().unwrap_or("").to_string();
                Ok(json!({ "text": text, "model": v["model"], "usage": v["usage"] }))
            }
            "ai.image" => {
                let path = args["path"].as_str().unwrap_or("");
                let mut body = json!({ "model": args["model"].as_str().unwrap_or(IMAGE_MODEL), "prompt": args["prompt"] });
                if let Some(a) = args["aspect_ratio"].as_str() {
                    body["aspect_ratio"] = json!(a);
                }
                let (status, bytes) = self.openrouter(Method::Post, &self.api("images"), Some(&body)).await?;
                if status != 200 {
                    return Err(failure(status, &bytes));
                }
                let v: Value = serde_json::from_slice(&bytes).map_err(|e| StepFail::Retry(format!("OpenRouter images: {e}")))?;
                let b64 = v["data"][0]["b64_json"].as_str().ok_or_else(|| StepFail::Retry("OpenRouter images: no image in the answer".into()))?;
                let image = base64::engine::general_purpose::STANDARD.decode(b64).map_err(|e| StepFail::Retry(format!("OpenRouter images: {e}")))?;
                if image.len() > MEDIA_MAX_BYTES {
                    return Err(permanent(format!("the image is over {MEDIA_MAX_BYTES} bytes")));
                }
                let mut out = self.store_media(run, index, path, image).await?;
                out["mediaType"] = v["data"][0]["media_type"].clone();
                Ok(out)
            }
            "ai.video.start" => {
                let mut body = json!({ "model": args["model"].as_str().unwrap_or(VIDEO_MODEL), "prompt": args["prompt"] });
                for k in ["duration", "resolution", "aspect_ratio"] {
                    if !args[k].is_null() {
                        body[k] = args[k].clone();
                    }
                }
                let (status, bytes) = self.openrouter(Method::Post, &self.api("videos"), Some(&body)).await?;
                if !matches!(status, 200 | 202) {
                    return Err(failure(status, &bytes));
                }
                let v: Value = serde_json::from_slice(&bytes).map_err(|e| StepFail::Retry(format!("OpenRouter videos: {e}")))?;
                Ok(json!({ "id": v["id"] }))
            }
            "ai.video.poll" => {
                let id = args["id"].as_str().ok_or_else(|| permanent("ai.video.poll needs the job id"))?;
                let (status, bytes) = self.openrouter(Method::Get, &self.api(&format!("videos/{id}")), None).await?;
                if status != 200 {
                    return Err(failure(status, &bytes));
                }
                let v: Value = serde_json::from_slice(&bytes).map_err(|e| StepFail::Retry(format!("OpenRouter videos: {e}")))?;
                Ok(json!({ "status": v["status"], "error": v["error"], "urls": v["unsigned_urls"], "usage": v["usage"] }))
            }
            "ai.video.save" => {
                let (id, path) = (args["id"].as_str().unwrap_or(""), args["path"].as_str().unwrap_or(""));
                let url = match args["url"].as_str() {
                    Some(u) if u.starts_with(&self.cfg.openrouter_url) => u.to_string(),
                    Some(u) => return Err(permanent(format!("the video is at {u}, outside OpenRouter"))),
                    None => self.api(&format!("videos/{id}/content?index=0")),
                };
                let (status, video) = self.openrouter(Method::Get, &url, None).await?;
                if status != 200 {
                    return Err(failure(status, &video));
                }
                if video.len() > MEDIA_MAX_BYTES {
                    return Err(permanent(format!("the video is over {MEDIA_MAX_BYTES} bytes")));
                }
                self.store_media(run, index, path, video).await
            }
            other => Err(permanent(format!("unknown step kind {other:?}"))),
        }
    }
}
