//! The app facet's `limits.js`: the limits and rules the platform code
//! (`cell/platform.mjs`) checks in the author's realm, generated from their
//! Rust definitions so the two cannot drift. Each rule's JavaScript sits
//! beside the Rust function it mirrors (`fragment_proto`, `blob`); this
//! module only puts them in one module. The in-app checks let an author
//! see a refusal while the mutation can still roll back; the supervisor's
//! own checks after the commit (`effects`) are the ones that hold. The
//! module is part of the platform code: the cell hashes it into the loader
//! id with `platform.js` (`cell/src/ops.rs`).

use std::fmt::Write;

use fragment_proto::{limits, RESERVED_OP_NAMES, VALID_KIND_JS, VALID_REPO_PATH_JS};

use crate::{blob, webpush};

/// The module's name beside `platform.js` and `app.js`.
pub const LIMITS_MODULE: &str = "limits.js";

/// JavaScript numbers are exact up to 2^53 - 1.
const JS_SAFE_INTEGER_MAX: u64 = (1 << 53) - 1;

/// Every limit the platform code reads, by its name there.
fn numbers() -> [(&'static str, u64); 10] {
    [
        ("RECORD_BODY_MAX_BYTES", limits::RECORD_BODY_MAX_BYTES as u64),
        ("EFFECTS_MAX", limits::EFFECTS_MAX as u64),
        ("RESULT_MAX_BYTES", limits::RESULT_MAX_BYTES as u64),
        ("APP_DB_MAX_BYTES", limits::APP_DB_MAX_BYTES),
        ("FILE_WRITE_MAX_BYTES", limits::FILE_WRITE_MAX_BYTES as u64),
        ("FILE_WRITES_MAX", limits::FILE_WRITES_MAX as u64),
        ("PATH_MAX_BYTES", limits::PATH_MAX_BYTES as u64),
        ("POINTER_MAX_BYTES", blob::POINTER_MAX_BYTES as u64),
        ("PUSH_WHO_MAX_CHARS", limits::PUSH_WHO_MAX_CHARS as u64),
        ("PUSH_PAYLOAD_MAX_BYTES", webpush::PAYLOAD_MAX_BYTES as u64),
    ]
}

/// A string's size in UTF-8 bytes, as the supervisor counts it (the rules
/// below use it).
const UTF8_BYTES_JS: &str = r#"export function utf8Bytes(text) {
  return new TextEncoder().encode(text).length;
}"#;

/// The text of `limits.js`.
pub fn limits_js() -> String {
    let mut out = String::from("// Generated by the cell from its Rust definitions (fragment_core::facet); not edited by hand.\n");
    for (name, value) in numbers() {
        assert!(value <= JS_SAFE_INTEGER_MAX, "{name} is exact as a JavaScript number");
        writeln!(out, "export const {name} = {value};").expect("writing to a String");
    }
    let reserved = serde_json::to_string(&RESERVED_OP_NAMES).expect("a list of names serializes");
    writeln!(out, "export const RESERVED_OP_NAMES = new Set({reserved});").expect("writing to a String");
    for rule in [UTF8_BYTES_JS, VALID_KIND_JS, VALID_REPO_PATH_JS, blob::IS_POINTER_JS] {
        out.push_str(rule);
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const PLATFORM_JS: &str = include_str!("../../../cell/platform.mjs");

    /// The names `export const|function <name>` declares.
    fn exports(module: &str) -> Vec<&str> {
        module
            .lines()
            .filter_map(|l| l.strip_prefix("export const ").or_else(|| l.strip_prefix("export function ")))
            .map(|rest| rest.split([' ', '(']).next().expect("a declaration names something"))
            .collect()
    }

    /// The names platform.mjs imports from `./limits.js`.
    fn imported() -> Vec<&'static str> {
        let from = PLATFORM_JS.find(r#"} from "./limits.js";"#).expect("platform.mjs imports from ./limits.js");
        let start = PLATFORM_JS[..from].rfind("import {").expect("the import opens") + "import {".len();
        PLATFORM_JS[start..from].split(',').map(str::trim).filter(|n| !n.is_empty()).collect()
    }

    #[test]
    fn every_name_platform_imports_is_exported_once() {
        let module = limits_js();
        let exported = exports(&module);
        let names = imported();
        assert!(!names.is_empty(), "platform.mjs reads its limits from limits.js");
        for name in &names {
            assert_eq!(exported.iter().filter(|e| *e == name).count(), 1, "limits.js exports {name} once");
        }
        // a module that failed to link would stop every app from loading
        assert_eq!(exported.len(), names.len(), "limits.js exports only what platform.mjs imports: {exported:?} vs {names:?}");
    }

    #[test]
    fn platform_defines_none_of_the_limits_itself() {
        for (name, _) in numbers() {
            assert!(!PLATFORM_JS.contains(&format!("const {name} =")), "platform.mjs redefines {name}");
        }
        for literal in ["64 * 1024", "256 * 1024", "16 * 1024 * 1024", "\"constructor\"", "git-lfs"] {
            assert!(!PLATFORM_JS.contains(literal), "platform.mjs spells out {literal} instead of importing it");
        }
    }

    #[test]
    fn the_values_are_the_rust_ones() {
        let module = limits_js();
        // literal numbers, not the constants: a changed limit shows up here
        for line in [
            "export const RECORD_BODY_MAX_BYTES = 65536;",
            "export const EFFECTS_MAX = 64;",
            "export const PATH_MAX_BYTES = 300;",
            "export const POINTER_MAX_BYTES = 200;",
            "export const PUSH_WHO_MAX_CHARS = 64;",
            "export const PUSH_PAYLOAD_MAX_BYTES = 3800;",
            r#"export const RESERVED_OP_NAMES = new Set(["constructor","fetch","alarm","webSocketMessage","webSocketClose","webSocketError"]);"#,
        ] {
            assert!(module.lines().any(|l| l == line), "{line}");
        }
    }
}
